### PR TITLE
Build for mpi_serial

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
🤞🏻

**Comment by xylar** [comment]
@zklaus, I think I've hit the limits of my knowledge here:
```
/home/conda/feedstock_root/build_artifacts/parallelio_1688046962669/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libmpi-serial.a(fort.o): warning: relocation against `mpiserial_' in read-only section `.text'
2023-06-29T13:58:25.6685394Z /home/conda/feedstock_root/build_artifacts/parallelio_1688046962669/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/parallelio_1688046962669/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libmpi-serial.a(fort.o): relocation R_X86_64_PC32 against symbol `mpiserial_' can not be used when making a shared object; recompile with -fPIC
2023-06-29T13:58:25.6686533Z /home/conda/feedstock_root/build_artifacts/parallelio_1688046962669/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: final link failed: bad value
2023-06-29T13:58:25.6694323Z collect2: error: ld returned 1 exit status
2023-06-29T13:58:25.6709927Z make[2]: *** [src/clib/CMakeFiles/pioc.dir/build.make:421: src/clib/libpioc.so] Error 1
2023-06-29T13:58:25.6716052Z make[1]: *** [CMakeFiles/Makefile2:206: src/clib/CMakeFiles/pioc.dir/all] Error 2
```
Seems to be something related to `mpi_serial` being build as a static library.  If you have a good sense of where/how to add the `-fPIC` flag, please feel free to push commits to this branch.

**Comment by xylar** [comment]
@mahf708, feel free to tinker with this, too, if you have any relevant expertise.  We can add you as a maintianer.

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by zklaus** [comment]
There is one more thing since also the `linux_64_mpimpi_serial` build is failing. However, it is not yet picking up the latest build (I was too impatient), so let's see where we land.

**Pull request merged**
