### PR TITLE
Bot pr arm osx h19434a

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@zklaus, just a quick note to say that I appreciate you working on this.  Feel free to add yourself as a maintainer.  I'm not particularly expert at building c/c++/fortran packages so I certainly could use the help.  We just needed Parallel-IO for ESMF so I kind of hacked it together as best I could.

**Comment by xylar** [comment]
@zklaus, just a quick note to say that I appreciate you working on this.  Feel free to add yourself as a maintainer.  I'm not particularly expert at building c/c++/fortran packages so I certainly could use the help.  We just needed Parallel-IO for ESMF so I kind of hacked it together as best I could.

**Comment by zklaus** [comment]
Cheers, @xylar. I am also mainly interested in ESMF. I hope to make some progress here and hopefully learn something about the cross-compiling machinery along the way. I know that you are very busy, but feel free to jump in with advice at any time.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
I think this works. @xylar, do you prefer to resolve it in the bot PR? In that case you can take the commits from here or add me as a maintainer in #9 so that I can do it myself. Alternatively we can merge here.

**Comment by zklaus** [comment]
This has been ported over to #4.

**Pull request closed without merging**
